root(app_0,nil).
rect(app_0,app).
contains(app_0,app_1).
text(app_1,(app).
str(app_1,"app").
contains(app_0,app_2).
circle(app_2,(app).
color(app_2,green).
contains(app_0,app_3).
rect(app_3,(app).
contains(app_3,app_4).
text(app_4,((app).
str(app_4,"inner").
contains(app_3,app_5).
circle(app_5,((app).
color(app_3,green).
contains(app_3,app_6).
circle(app_6,((app).
color(app_3,yellow).
contains(app_0,app_7).
circle(app_7,(app).
color(app_7,yellow).
contains(app_0,app_8).
connector(app_8,(app).
sender(app_8,(app).
receiver(app_8,((app).
contains(app_0,app_9).
connector(app_9,(app).
sender(app_9,((app).
receiver(app_9,(app).
contains(app_0,app_10).
ignore(app_10,(app).
contains(app_0,app_11).
ignore(app_11,(app).
contains(app_0,app_12).
connector(app_12,(app).
sender(app_12,(app).
receiver(app_12,((app).
contains(app_0,app_13).
connector(app_13,(app).
sender(app_13,((app).
receiver(app_13,(app).
contains(app_0,app_14).
rect(app_14,(app).
contains(app_14,app_15).
text(app_15,(hwsub).
str(app_15,"sub").
contains(app_14,app_16).
circle(app_16,(hwsub).
color(app_16,green).
contains(app_14,app_17).
circle(app_17,(hwsub).
color(app_17,yellow).
contains(app_14,app_18).
rect(app_18,(hwsub).
contains(app_18,app_19).
circle(app_19,((sub).
color(app_19,green).
contains(app_18,app_20).
circle(app_20,((sub).
color(app_20,yellow).
contains(app_14,app_21).
connector(app_21,(hwsub).
sender(app_21,(hwsub).
receiver(app_21,((hwsub).
contains(app_14,app_22).
connector(app_22,(hwsub).
sender(app_22,((hwsub).
receiver(app_22,(hwsub).
contains(app_14,app_23).
ignore(app_23,(hwsub).
contains(app_14,app_24).
ignore(app_24,(hwsub).
contains(app_14,app_25).
rect(app_25,((hwsub).
color(app_25,red).
contains(app_25,app_26).
text(app_26,((hwsub).
str(app_26,"greet").
contains(app_25,app_27).
circle(app_27,(((hwsub).
color(app_27,green).
contains(app_25,app_28).
circle(app_28,(((hwsub).
color(app_28,yellow).
contains(app_14,app_29).
circle(app_29,((hwsub).
color(app_29,green).
contains(app_14,app_30).
circle(app_30,((hwsub).
color(app_30,yellow).
contains(app_0,app_31).
connector(app_31,(hwhello).
sender(app_31,(hwhello).
receiver(app_31,((hwhello).
contains(app_0,app_32).
connector(app_32,(hwhello).
sender(app_32,((hwhello).
receiver(app_32,(hwhello).
