namespacedescriptor(fact_1,nil).
subject(fact_1,nsd_2).
object(fact_1,nil).
ns(fact_2,nil).
subject(fact_2,nsd_2).
object(fact_2,i).
component(fact_3,nil).
subject(fact_3,nsd_2).
object(fact_3,root).
name(fact_4,nil).
subject(fact_4,nd_3).
object(fact_4,nil).
namestr(fact_5,nil).
subject(fact_5,nd_3).
object(fact_5,"x").

namespace(fact_6,nil).
subject(fact_6,nd_3).
object(fact_6,nsd_2).

namespacedescriptor(fact_7,nil).
subject(fact_7,nsd_5).
object(fact_7,nil).
ns(fact_8,nil).
subject(fact_8,nsd_5).
object(fact_8,o).
component(fact_9,nil).
subject(fact_9,nsd_5).
object(fact_9,root).
name(fact_10,nil).
subject(fact_10,nd_6).
object(fact_10,nil).
namestr(fact_11,nil).
subject(fact_11,nd_6).
object(fact_11,"y").
namespace(fact_12,nil).
subject(fact_12,nd_6).
object(fact_12,nsd_5).
root(fact_13,nil).
subject(fact_13,sub_0).
object(fact_13,nil).
rect(fact_14,nil).
subject(fact_14,sub_0).
object(fact_14,sub).
contains(fact_15,nil).
subject(fact_15,sub_0).
object(fact_15,sub_1).
rect(fact_16,nil).
subject(fact_16,sub_1).
object(fact_16,nd_3).
contains(fact_17,nil).
subject(fact_17,sub_0).
object(fact_17,sub_4).
rect(fact_18,nil).
subject(fact_18,sub_4).
object(fact_18,nd_6).
