(defun new-hw123 ()
  (let ((hw123 (new-hwapp))                
        (inner (new-hw23)))
    (add-connection inner (new-connection "./in" (lambda (self m) (send-downward self "./c/1/xx" m))))
    (add-connection inner (new-connection "./c/1/i/yy" (lambda (self m) (send-upward self "./c/1/o/b" m))))
    (setter-kind hw123 "hw123")
    (add-child hw123 "./c/1" hw23)
    hw123))
